# Generated by Django 3.2 on 2021-07-28 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdministrationApp', '0002_mobileregistration'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MobileRegistration',
            new_name='QuickAppointment',
        ),
    ]
