# Generated by Django 3.2 on 2021-07-28 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdministrationApp', '0003_rename_mobileregistration_quickappointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=400, null=True)),
                ('age', models.CharField(blank=True, max_length=400, null=True)),
                ('remark', models.CharField(blank=True, max_length=1000, null=True)),
                ('place', models.CharField(blank=True, max_length=400, null=True)),
                ('mobile', models.CharField(blank=True, max_length=400, null=True)),
                ('other_contact', models.CharField(blank=True, max_length=400, null=True)),
                ('booking_date', models.DateField(blank=True, null=True)),
                ('submit_date', models.DateField(blank=True, null=True)),
                ('flag', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
