# Generated by Django 3.2 on 2021-07-29 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdministrationApp', '0004_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=400, null=True)),
                ('age', models.CharField(blank=True, max_length=400, null=True)),
                ('place', models.CharField(blank=True, max_length=400, null=True)),
                ('username', models.CharField(blank=True, max_length=1000, null=True)),
                ('password', models.CharField(blank=True, max_length=1000, null=True)),
                ('email', models.EmailField(blank=True, max_length=400, null=True)),
                ('mobile1', models.CharField(blank=True, max_length=400, null=True)),
                ('mobile2', models.CharField(blank=True, max_length=400, null=True)),
                ('submit_date', models.DateField(blank=True, null=True)),
                ('is_staff', models.BooleanField(blank=True, default=False, null=True)),
                ('is_nurse', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
