# Generated by Django 3.2 on 2021-07-29 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdministrationApp', '0005_nurse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nurse',
            old_name='mobile2',
            new_name='remark',
        ),
    ]
