# Generated by Django 3.2 on 2021-07-31 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdministrationApp', '0007_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorsProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=400, null=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='doctors/')),
                ('mobile', models.CharField(blank=True, max_length=400, null=True)),
                ('email', models.EmailField(blank=True, max_length=400, null=True)),
                ('designation', models.CharField(blank=True, max_length=400, null=True)),
                ('snippets', models.CharField(blank=True, max_length=400, null=True)),
                ('facebook_url', models.CharField(blank=True, max_length=400, null=True)),
                ('instagram_url', models.CharField(blank=True, max_length=400, null=True)),
                ('twitter_url', models.CharField(blank=True, max_length=400, null=True)),
                ('telegram_url', models.CharField(blank=True, max_length=400, null=True)),
            ],
        ),
    ]
