# Generated by Django 3.2 on 2021-07-31 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdministrationApp', '0008_doctorsprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorsprofile',
            old_name='telegram_url',
            new_name='linkedin_url',
        ),
    ]
