# Generated by Django 3.2 on 2021-07-31 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdministrationApp', '0009_rename_telegram_url_doctorsprofile_linkedin_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=400, null=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='feedback/')),
                ('Role', models.CharField(blank=True, max_length=400, null=True)),
                ('snippets', models.CharField(blank=True, max_length=400, null=True)),
            ],
        ),
    ]
