# Generated by Django 3.2 on 2021-08-04 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdministrationApp', '0011_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=400, null=True)),
                ('submit_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
