# Generated by Django 3.2 on 2021-08-08 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdministrationApp', '0012_subscribe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, max_length=400, null=True)),
                ('item_photo', models.ImageField(blank=True, null=True, upload_to='doctors/')),
                ('item_price', models.CharField(blank=True, max_length=400, null=True)),
                ('offer_price', models.CharField(blank=True, max_length=400, null=True)),
                ('item_category', models.CharField(blank=True, max_length=400, null=True)),
                ('item_snippets', models.CharField(blank=True, max_length=400, null=True)),
                ('item_rating', models.CharField(blank=True, max_length=400, null=True)),
            ],
        ),
    ]
