# Generated by Django 3.2 on 2021-08-08 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdministrationApp', '0014_alter_shop_item_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='submit_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
