# Generated by Django 3.2 on 2021-08-08 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdministrationApp', '0015_shop_submit_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='item_category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='item_name',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='item_photo',
            new_name='item_Image',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='item_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='item_rating',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='item_snippets',
            new_name='snippets',
        ),
    ]
