# Generated by Django 3.2 on 2021-08-08 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdministrationApp', '0016_auto_20210808_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='submit_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
