# Generated by Django 3.2 on 2021-08-08 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdministrationApp', '0017_alter_shop_submit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='submit_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
