# Generated by Django 3.2 on 2021-08-08 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdministrationApp', '0018_alter_shop_submit_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=400, null=True)),
                ('mobile', models.CharField(blank=True, max_length=400, null=True)),
                ('product_id', models.CharField(blank=True, max_length=400, null=True)),
                ('price', models.CharField(blank=True, max_length=400, null=True)),
                ('offer_price', models.CharField(blank=True, max_length=400, null=True)),
                ('request_date', models.DateField(auto_now_add=True)),
                ('is_read', models.BooleanField(blank=True, default=False, null=True)),
                ('is_delivered', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
