# Generated by Django 3.2 on 2021-09-04 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdministrationApp', '0019_shoprequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounterValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docter_count', models.CharField(blank=True, max_length=400, null=True)),
                ('department_count', models.CharField(blank=True, max_length=400, null=True)),
                ('reserchlab_count', models.CharField(blank=True, max_length=400, null=True)),
                ('awards_count', models.CharField(blank=True, max_length=400, null=True)),
                ('submit_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
