# Generated by Django 3.2 on 2021-09-09 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdministrationApp', '0021_rename_snippets_shop_discription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='discription',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
