# Generated by Django 3.2 on 2021-09-09 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdministrationApp', '0022_alter_shop_discription'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleMeet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=400, null=True)),
                ('link', models.CharField(blank=True, max_length=400, null=True)),
                ('submit_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
