# Generated by Django 3.2 on 2021-09-11 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdministrationApp', '0023_googlemeet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo_name', models.CharField(blank=True, max_length=400, null=True)),
                ('todo_dead_time', models.CharField(blank=True, max_length=400, null=True)),
                ('todo_subject', models.CharField(blank=True, max_length=400, null=True)),
                ('todo_body', models.CharField(blank=True, max_length=400, null=True)),
                ('todo_status', models.CharField(blank=True, max_length=400, null=True)),
                ('submit_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
