# Generated by Django 3.2 on 2021-09-11 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdministrationApp', '0024_todo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_body', models.CharField(blank=True, max_length=400, null=True)),
                ('submit_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
