# Generated by Django 3.2 on 2021-09-13 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdministrationApp', '0025_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoprequest',
            name='shop_status',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
