# Generated by Django 3.2 on 2021-09-27 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdministrationApp', '0026_shoprequest_shop_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(blank=True, max_length=200, null=True)),
                ('total_amount', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('start_Date', models.DateField(blank=True, null=True)),
                ('end_Date', models.DateField(blank=True, null=True)),
                ('flage', models.BooleanField(blank=True, default=True, null=True)),
            ],
        ),
    ]
