# Generated by Django 3.2 on 2021-09-27 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdministrationApp', '0027_accounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='total_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
