# Generated by Django 3.2 on 2021-09-27 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdministrationApp', '0028_auto_20210927_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='total_amount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
