# Generated by Django 3.2 on 2021-09-28 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdministrationApp', '0029_alter_accounts_total_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounts',
            old_name='amount',
            new_name='expense',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='flage',
        ),
        migrations.AddField(
            model_name='accounts',
            name='expense_flag',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='accounts',
            name='income',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accounts',
            name='income_flag',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
