# Generated by Django 3.2 on 2021-09-28 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdministrationApp', '0030_auto_20210928_1931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounts',
            old_name='total_amount',
            new_name='total_expense',
        ),
        migrations.AddField(
            model_name='accounts',
            name='total_income',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
