# Generated by Django 3.2 on 2021-09-28 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdministrationApp', '0031_auto_20210928_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='expense',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='income',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
