# Generated by Django 3.2 on 2021-09-30 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdministrationApp', '0032_auto_20210928_1955'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter', models.CharField(blank=True, max_length=400, null=True)),
                ('facebook', models.CharField(blank=True, max_length=400, null=True)),
                ('instagram', models.CharField(blank=True, max_length=400, null=True)),
                ('google_plus', models.CharField(blank=True, max_length=400, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=400, null=True)),
                ('submit_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
